カナを返すオプションの追加
rinkei/jipcode pull request #17
Opened 2023-05-16 05:51 UTC by reud

## やったこと

- 郵便番号と対応する住所のデータに全角カナを追加しました

## 目的

- 住所入力フォームには、全角や半角カナを入力する場面があるため

## やらないこと

- 大口事業所個別番号データは都道府県、市区町村、町域までを返す
  - 郵便局の持つ大口事業所個別番号データにはカナ表記が含まれていないため
  - 都道府県、市区町村、町域は郵便番号が持つカナ表記を利用して辞書を引いている

## できるようになること（ユーザ目線）

- 住所入力フォームの実装時にカナが必要なケースにおいて、ある程度まで自動入力出来る

## 動作確認

- `./bin/console` で動作確認をしました
- テストの更新を行っています

2023-05-16 05:53 UTC, reud commented
レビューについてですが、https://github.com/rinkei/jipcode/pull/17/commits/9745b4bb1c2522a06a8dd081801709156a85f953 を見ると読みやすいと思います。
csv更新のコミットとコード更新のコミットを分けているため・・・

2023-05-29 00:57 UTC, rinkei requested changes
PRありがとうございます。
カナデータはいずれ要望があればと考えていたので助かります。
ただ、現時点で一点課題があり、コメントを記載しているので確認お願いします。

2023-05-29 00:57 UTC, rinkei commented on lib/jipcode/japan_post.rb
> +        town_kana       = kana_dict[row[5]] # [MEMO] 番地に対してのカナは提供しない
例えば「本町」という町域は、東京都小金井市では「ホンチョウ」と読みますが、東京都渋谷区では「ホンマチ」と読みます。
そのため次のような誤ったデータが登録されることがあります。
```
1848577,東京都,小金井市,本町６丁目５−３シャトー小金井１Ｆ,トウキョウト,コガネイシ,ホンマチ
```

事業所データの町域についてはキャッシュでカナを与えなくても良いかもしれません。

2023-05-29 06:48 UTC, reud commented on lib/jipcode/japan_post.rb
> +        town_kana       = kana_dict[row[5]] # [MEMO] 番地に対してのカナは提供しない
レビューありがとうございます！

浅学故に知らなかったのですが、同形異音語が町域データにあるのですね・・・・

町域データは提供しない。で私も良いと思うので更新します！

2023-05-29 07:28 UTC, reud commented on lib/jipcode.rb
> +      address[:town_kana]       = address_param[6] || ""
[MEMO]
文字列結合などに使われることを想定するとnilを返すより空文字列を返してあげる方が親切そうなのでこのように書いている

2023-06-30 13:38 UTC, rinkei approved these changes

2023-06-30 13:39 UTC, merged